# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=180, null=True)),
                ('modelId', models.BigIntegerField(blank=True, null=True)),
                ('manufactureId', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='carRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.BigIntegerField(blank=True, null=True)),
                ('car', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='carType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carTypeName', models.CharField(max_length=180, null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturerName', models.CharField(max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manufacturerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=256, null=True)),
                ('manufacturing_date', models.DateTimeField(null=True)),
                ('manufacturer_name', models.CharField(max_length=256, null=True)),
                ('fuel_type', models.CharField(max_length=56, null=True)),
                ('vehicle_color', models.CharField(max_length=56, null=True)),
                ('km_run', models.CharField(max_length=256, null=True)),
                ('rc', models.FileField(blank=True, null=True, upload_to=b'')),
                ('fitness', models.FileField(blank=True, null=True, upload_to=b'')),
                ('permit', models.FileField(blank=True, null=True, upload_to=b'')),
                ('insurance', models.FileField(blank=True, null=True, upload_to=b'')),
                ('pollution', models.FileField(blank=True, null=True, upload_to=b'')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.carModel')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.carType')),
            ],
        ),
        migrations.CreateModel(
            name='mstCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelId', models.BigIntegerField(blank=True, null=True)),
                ('ownerId', models.BigIntegerField(blank=True, null=True)),
                ('rentTypeFlag', models.BooleanField(default=True)),
                ('rentValue', models.BigIntegerField(blank=True, null=True)),
                ('carType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carType')),
            ],
        ),
        migrations.CreateModel(
            name='mstRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredUserId', models.BigIntegerField(blank=True, null=True)),
                ('registeredCarId', models.BigIntegerField(blank=True, null=True)),
                ('registrationStartDate', models.DateTimeField(blank=True, null=True)),
                ('registrationEndDate', models.DateTimeField(blank=True, null=True)),
                ('registrationStatusId', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mstRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.BigIntegerField(blank=True, null=True)),
                ('destination', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, null=True)),
            ],
        ),
    ]
