# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='manufacturerregistration',
            name='rateList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rateList'),
        ),
    ]
