# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190210_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ownerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('mobileNumber', models.BigIntegerField(null=True)),
                ('licenseNumber', models.CharField(max_length=256, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('aadharCardFront', models.FileField(blank=True, null=True, upload_to=b'')),
                ('aadharCardBack', models.FileField(blank=True, null=True, upload_to=b'')),
                ('licenseFront', models.FileField(blank=True, null=True, upload_to=b'')),
                ('licenseBack', models.FileField(blank=True, null=True, upload_to=b'')),
                ('photo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('addressProof', models.FileField(blank=True, null=True, upload_to=b'')),
                ('normsAccepted', models.BooleanField(default=True)),
            ],
        ),
    ]
