# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ownerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='manufacturerregistration',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fuelType'),
        ),
        migrations.AlterField(
            model_name='manufacturerregistration',
            name='vehicle_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vehicleColour'),
        ),
    ]
