# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190216_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerregistration',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.manufacturerRegistration'),
        ),
    ]
