# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-16 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ownerregistration_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerregistration',
            name='manufacturer_name',
        ),
        migrations.AddField(
            model_name='manufacturerregistration',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer'),
        ),
    ]
