# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190216_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerregistration',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer'),
        ),
        migrations.AlterField(
            model_name='manufacturerregistration',
            name='rateList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rateList'),
        ),
    ]
