# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190219_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='manufactureId',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='modelId',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer'),
        ),
    ]
